  
name: 'Build & Deploy Helm chart to EKS'
on:
  push:
    branches:
      - master
env:
  DOCKER_ID: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_PW: ${{ secrets.DOCKERHUB_PASSWD }}
jobs:
  backend:
    name: BUILD 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jobsService  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}
    - uses: actions/checkout@v2
    - name: build image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USER}}/bc16:latest
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USER }}/bc16:latest